# Logger.
[logger]
    path        = "./data/log/gf-app"
    level       = "info"
    stdout      = true

# Database.
[database]
    [[database.default]]
        type = "mysql"
        link  = "root:root@tcp(127.0.0.1:3306)/arco-demo?charset=utf8mb4&parseTime=true&loc=Local"
        role = "master"
        timezone= "Asia/Shanghai"
        debug = true
    [[database.default]]
        type = "mysql"
        link  = "root:root@tcp(127.0.0.1:3306)/arco-demo?charset=utf8mb4&parseTime=true&loc=Local"
        role = "slave"
        timezone= "Asia/Shanghai"
        debug = true
    # Database logger.
    [database.logger]
        Path   = "./data/log/gf-app/sql"
        Level  = "debug"
        Stdout = false

# Redis数据库配置
[redis]
    open = true #是否开启 redis 缓存 若不开启使用gchache缓存方式
    [redis.default]
        host = "127.0.0.1:6379"
