// Code generated by gf-codegen. DO NOT EDIT.
// 实体类 entity
// 生成日期：2022-12-23 18:36:40
// 生成人：Wumengye
package entity

import (
    "github.com/gogf/gf/v2/os/gtime"
	"github.com/gogf/gf/v2/util/gmeta"
)

// VideoCollectionTwoPks is the golang structure for table demo_video_collection_two_pks.
type VideoCollectionTwoPks struct {
	gmeta.Meta   `orm:"table:demo_video_collection_two_pks"`
    Id1    string         `orm:"id1,primary" json:"id1"`    // 视频集ID1
    Id2    string         `orm:"id2,primary" json:"id2"`    // 视频集ID2
    ContentType    string         `orm:"content_type" json:"contentType"`    // 内容类型
    FilterType    string         `orm:"filter_type" json:"filterType"`    // 筛选类型
    Count    uint32         `orm:"count" json:"count"`    // 集合内视频数量
    IsOnline    bool         `orm:"is_online" json:"isOnline"`    // 是否上线：0 未上线|1 已上线
    CreatedAt    *gtime.Time         `orm:"created_at" json:"createdAt"`    // 创建时间
    UpdatedAt    *gtime.Time         `orm:"updated_at" json:"updatedAt"`    // 更新时间
}

