// Code generated by gf-codegen. DO NOT EDIT.
// 实体类 entity
// 生成日期：2022-12-23 18:36:40
// 生成人：Wumengye
package entity

import (
    "github.com/gogf/gf/v2/os/gtime"
	"github.com/gogf/gf/v2/util/gmeta"
)

// VideoCollection is the golang structure for table demo_video_collection.
type VideoCollection struct {
	gmeta.Meta   `orm:"table:demo_video_collection"`
    Id    string         `orm:"id,primary" json:"id"`    // 视频集ID，字符串格式
    Name    string         `orm:"name" json:"name"`    // 视频集名称
    ContentType    string         `orm:"content_type" json:"contentType"`    // 内容类型
    FilterType    string         `orm:"filter_type" json:"filterType"`    // 筛选类型
    Count    uint32         `orm:"count" json:"count"`    // 集合内视频数量
    IsOnline    bool         `orm:"is_online" json:"isOnline"`    // 是否上线：0 未上线|1 已上线
    CreatedAt    *gtime.Time         `orm:"created_at" json:"createdAt"`    // 创建时间
    UpdatedAt    *gtime.Time         `orm:"updated_at" json:"updatedAt"`    // 更新时间
}

