apiVersion: v1
table:
    name: demo_video_collection_two_pks
    comment: ""
    backendPackage: arco-demo/app
    frontendModule: arco-demo
    templateCategory: crud
    businessName: video_collection_two_pks
    functionAuthor: Wumengye
    overwrite: true
    sortColumn: id
    sortType: asc
    showDetail: false         # 是否支持显示详情(本开关仅当生成前端页面时生效)
    isRpc: false             # 是否生成rpc服务方式的代码
    separatePackage: false   # 是否将每个表的代码生成到单独目录下
    createTime: 2022-12-23 18:36:40
    updateTime: 2022-12-23 18:36:40
columns:
    id1:
        sort: 1
        comment: "视频集ID1"
        sqlType: varchar(50)
        isPk: true
        isRequired: true
    id2:
        sort: 2
        comment: "视频集ID2"
        sqlType: varchar(50)
        isPk: true
        isRequired: true
    content_type:
        sort: 3
        comment: "内容类型"
        sqlType: varchar(50)
        isRequired: true
    filter_type:
        sort: 4
        comment: "筛选类型"
        sqlType: varchar(50)
    count:
        sort: 5
        comment: "集合内视频数量"
        sqlType: int unsigned
    is_online:
        sort: 6
        comment: "是否上线：0 未上线|1 已上线"
        sqlType: bit(1)
    created_at:
        sort: 7
        comment: "创建时间"
        sqlType: timestamp(6)
    updated_at:
        sort: 8
        comment: "更新时间"
        sqlType: timestamp(6)
listColumns:
    id1:
        sort: 1
        minWidth: 100
        isOverflowTooltip: true
    id2:
        sort: 2
        minWidth: 100
        isOverflowTooltip: true
    content_type:
        sort: 3
        minWidth: 100
        isOverflowTooltip: true
    filter_type:
        sort: 4
        minWidth: 100
        isOverflowTooltip: true
    count:
        sort: 5
        minWidth: 100
        isOverflowTooltip: true
    is_online:
        sort: 6
        minWidth: 100
        isOverflowTooltip: true
    created_at:
        sort: 7
        minWidth: 100
        isOverflowTooltip: true
    updated_at:
        sort: 8
        minWidth: 100
        isOverflowTooltip: true
addColumns:
    id1:
        sort: 1
    id2:
        sort: 2
    content_type:
        sort: 3
    filter_type:
        sort: 4
    count:
        sort: 5
    is_online:
        sort: 6
    created_at:
        sort: 7
    updated_at:
        sort: 8
editColumns:
    id1:
        sort: 1
        isDisabled: true
    id2:
        sort: 2
    content_type:
        sort: 3
    filter_type:
        sort: 4
    count:
        sort: 5
    is_online:
        sort: 6
    created_at:
        sort: 7
    updated_at:
        sort: 8
queryColumns:
    id1:
        sort: 1
    id2:
        sort: 2
    content_type:
        sort: 3
    filter_type:
        sort: 4
    count:
        sort: 5
    is_online:
        sort: 6
    created_at:
        sort: 7
    updated_at:
        sort: 8
detailColumns:
    id1:
        sort: 1
        colSpan: 12
    id2:
        sort: 2
        colSpan: 12
    content_type:
        sort: 3
        colSpan: 12
    filter_type:
        sort: 4
        colSpan: 12
    count:
        sort: 5
        colSpan: 12
    is_online:
        sort: 6
        colSpan: 12
    created_at:
        sort: 7
        colSpan: 12
    updated_at:
        sort: 8
        colSpan: 12
    